server:
  port: 8080
  servlet:
    context-path: /financial

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: postgres
    password: admin



  liquibase:
    change-log=classpath:db/changelog/changelog:
      sql: